
    enum YesNoPending{
        Yes
        No
        Pending
        DontKnow
    }
    enum StaffType{
        FY1
        FY2
        ACCS
        Core
        Int
        Higher
        SAS
        Consultant
    }
    scalar Date

    type User{
        id:ID
        userName:String
        realName:String
        email:String
        category:StaffType
        isAdmin:Boolean
    }
    type Category{
        id:ID 
        name:String
    }

    type Project{
        title: String!
	    proposers: [User]!
	    description: String!
	    propdate: Date!
	    methodology: String!
	    category: [Category]
	    othertags: [String]
	    leader: User
	    email: String
	    peopleinvolved: [User]
	    advertise: Boolean
	    mm_or_ci: Boolean
	    caldicott: YesNoPending
	    research: YesNoPending
	    startdate: Date
	    finishdate: Date
        candisplay: Date
    }
type Query {
    getLoggedInUser:User
    getProject(id:ID):Project
    projectList:[Project]
    allUsers: [User!]!
    getUser(id:ID):User
}
