const taglist={	airway:'Airway',
				cc:'Critical Care',
				ci:'Critical incidents',
				ds:'Day surgery',
				ed:'Education & training',
				ent:'Ear, nose & throat',
				eq:'Equipment',
				gs:'General surgery',
				gyn:'Gynaecology',
				mgt:'Management',
				obs:'Obstetrics',
				ortho:'Orthopaedics',
				pain:'Pain',
				pom:'Peri-operative medicine',
				qi:'Quality improvement',
				reg:'Regional',
				trauma:'Trauma',
				urol:'Urology',
				vasc:'Vascular',
				other:'Other'}
				
export default taglist